"""Equivalence tests: Python VM vs C++ VM (pushgp_cpp_seeder).

For every randomly generated program and a battery of identical inputs,
the two VMs must produce bit-identical float64 outputs (or both None on
fault).  Programs are generated by Python's `RandomProgramGenerator` so
tree shape is exactly the same on both sides.

Run:
    python tests/test_vm_equivalence.py        # quick (200 progs * 5 inputs)
    python tests/test_vm_equivalence.py 2000   # heavier
"""
from __future__ import annotations

import struct
import sys
from pathlib import Path

import numpy as np

# Make the project importable without install.
HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent           # research/bp-deocder-synthesis
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "cpp_seeder"))   # for the .pyd

from pushgp.genome import program_to_list
from pushgp.random_program import RandomProgramGenerator, V2C_INSTR, C2V_INSTR
from pushgp.vm import VM
import pushgp_cpp_seeder as M


def bits(x: float) -> bytes:
    return struct.pack("<d", x)


def py_run(prog, side, incoming, L_v, deg, iter_idx, evo):
    vm = VM()
    vm.state.ctx_channel_llr = float(L_v)
    vm.state.ctx_has_channel_llr = (side == "v2c")
    vm.state.ctx_incoming = incoming.astype(np.float64, copy=True)
    vm.state.ctx_deg = int(deg)
    vm.state.ctx_iter = int(iter_idx)
    vm.state.ctx_max_iter = 25
    vm.state.ctx_noise_var = 1.0
    vm.state.ctx_edge_index = 0
    vm.state.ctx_code_rate = 0.5
    vm.state.ctx_evo_constants = evo.astype(np.float64, copy=True)
    if side == "v2c":
        vm.state.floats.push(float(L_v))
        vm.state.ints.push(0)            # edge_index
        vm.state.ints.push(int(deg))
        vm.state.ints.push(int(iter_idx))
        vm.state.ints.push(25)
        vm.state.fvecs.push(incoming.astype(np.float64, copy=True))
    else:
        vm.state.ctx_has_channel_llr = False
        vm.state.ints.push(0)
        vm.state.ints.push(int(deg))
        vm.state.ints.push(int(iter_idx))
        vm.state.ints.push(25)
        vm.state.fvecs.push(incoming.astype(np.float64, copy=True))
    return vm.run(prog)


def main(n_progs: int = 200, n_inputs: int = 5, seed: int = 12345) -> int:
    rng = np.random.default_rng(seed)
    rpg = RandomProgramGenerator(np.random.default_rng(seed))
    deg = 8

    mismatches = []
    fault_agree = 0
    finite_agree = 0
    total = 0

    for k in range(n_progs):
        side = "v2c" if (k % 2 == 0) else "c2v"
        instr = V2C_INSTR if side == "v2c" else C2V_INSTR
        size = int(rng.integers(4, 25))
        prog = rpg.random_program(instr, size, size + 5)
        prog_dict = program_to_list(prog)
        cpp_h = M.build_program(prog_dict)

        for j in range(n_inputs):
            incoming = rng.uniform(-3.0, 3.0, size=deg - 1).astype(np.float64)
            L_v = float(rng.uniform(-2.0, 2.0))
            iter_idx = int(rng.integers(0, 8))
            evo = rng.uniform(-3.0, 3.0, size=8).astype(np.float64)

            py_out = py_run(prog, side, incoming, L_v, deg, iter_idx, evo)
            cpp_out = M.run_program(cpp_h, side, evo, incoming, L_v, deg, iter_idx)
            total += 1

            if py_out is None and cpp_out is None:
                fault_agree += 1
                continue
            if py_out is None or cpp_out is None:
                mismatches.append((k, j, side, "fault disagreement", py_out, cpp_out))
                continue
            if bits(py_out) != bits(cpp_out):
                mismatches.append((k, j, side, "bits differ", py_out, cpp_out))
                continue
            finite_agree += 1

    print(f"total={total} finite_agree={finite_agree} "
          f"fault_agree={fault_agree} mismatches={len(mismatches)}")
    if mismatches:
        for m in mismatches[:20]:
            print(" ", m)
        return 1
    return 0


if __name__ == "__main__":
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 200
    sys.exit(main(n_progs=n))
